"use client";
import { useEffect, useState } from "react";
type Deployment = { id: string; repository: string; pullRequest: number; commitSha: string; state: string; createdAt: string };
const sections = ["Overview", "Projects", "Deployments", "Build history", "Audit log", "Settings"];
export default function Dashboard() {
 const [items,setItems]=useState<Deployment[]>([]); const [error,setError]=useState(""); const [section,setSection]=useState("Overview"); const [showConnect,setShowConnect]=useState(false);
 useEffect(()=>{fetch(process.env.NEXT_PUBLIC_API_URL??"http://localhost:8080/api/v1/deployments").then(r=>r.ok?r.json():Promise.reject(r.statusText)).then(setItems).catch(()=>setError("The API is unavailable. Start the PreviewDock API to view live deployments."))},[]);
 return <main><aside><strong>PREVIEWDOCK</strong><span>Every PR, ready to review.</span><nav aria-label="Workspace navigation">{sections.map(item=><button key={item} type="button" className={section===item?"active":""} onClick={()=>setSection(item)}>{item}</button>)}</nav></aside><section><header><div><p className="eyebrow">WORKSPACE · {section.toUpperCase()}</p><h1>{section==="Overview"?"Deployment overview":section}</h1><p>Live pull-request environments across your organization.</p></div><button type="button" onClick={()=>setShowConnect(true)}>Connect repository</button></header>{section!=="Overview"?<div className="table"><div className="tablehead"><h2>{section}</h2></div><p className="empty">This section will show live API data when the PreviewDock backend is running.</p></div>:<><div className="summary"><article><small>ACTIVE PREVIEWS</small><b>{items.filter(i=>i.state==="READY").length}</b></article><article><small>QUEUED WORK</small><b>{items.filter(i=>i.state!=="READY").length}</b></article><article><small>SECURITY POSTURE</small><b className="good">Protected</b></article></div><div className="table"><div className="tablehead"><h2>Recent deployments</h2><span>Real-time data</span></div>{error?<p className="empty">{error}</p>:items.length===0?<p className="empty">No deployments yet. Connect a GitHub App installation and open a pull request.</p>:items.map(d=><button type="button" className="row" key={d.id} onClick={()=>setSection("Deployments")}><div><b>{d.repository}</b><small>Pull request #{d.pullRequest} · {d.commitSha.slice(0,12)}</small></div><span className={'state '+d.state.toLowerCase()}>{d.state}</span><time>{new Date(d.createdAt).toLocaleString()}</time></button>)}</div></>}</section>{showConnect&&<div className="dialog-backdrop" role="presentation" onMouseDown={()=>setShowConnect(false)}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="connect-title" onMouseDown={e=>e.stopPropagation()}><button className="close" type="button" aria-label="Close" onClick={()=>setShowConnect(false)}>×</button><p className="eyebrow">GITHUB APP</p><h2 id="connect-title">Connect a repository</h2><p>Repository connection requires a configured GitHub App. Add its credentials to your secure server environment, then use the API to authorize an installation.</p><a className="docs-link" href="https://docs.github.com/en/apps/creating-github-apps" target="_blank" rel="noreferrer">Open GitHub App documentation →</a></section></div>}</main>;
}
